{
  "name": "affimania-ai-automation",
  "version": "2.5.0",
  "description": "2026 AI-Powered Script for 40+ Amazon Deals.",
  "main": "update_deals.js",
  "scripts": {
    "start": "node update_deals.js"
  },
  "author": "Affimania Ai",
  "license": "MIT",
  "dependencies": {
    "amazon-paapi": "^1.0.1",
    "fs-extra": "^11.1.0"
  }
}{
  "name": "affimania-ai-automation",
  "version": "2.5.0",
  "description": "2026 AI-Powered Script for 40+ Amazon Deals.",
  "main": "update_deals.js",
  "scripts": {
    "start": "node update_deals.js"
  },
  "author": "Affimania Ai",
  "license": "MIT",
  "dependencies": {
    "amazon-paapi": "^1.0.1",
    "fs-extra": "^11.1.0"
  }
}
